version: 2.1
executors:
  builder:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  build:
    executor: builder

    steps:
      - run: echo "Ignore gh-pages branch"


workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages

