version: 2.1
executors:
  builder:
    docker:
      - image: cimg/openjdk:8.0

#    environment:
#      JVM_OPTS: -Xmx16g
#      TERM: dumb

jobs:
  build:
    executor: builder
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bb:13:00:be:ea:3a:eb:00:9b:e4:68:6c:85:25:39:26"

      - checkout

      - run: git submodule sync

      - run: git submodule update --init

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: ./gradlew dist

      - run:
          command: .circleci/publish.sh

      - persist_to_workspace:
          root: build
          paths:
            - distributions

  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${VERSION} ./artifacts/distributions/


workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            branches:
              ignore: gh-pages
  deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.+/

